server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: ecommerce

spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/ecommerce_media?authSource=admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

jwt:
  secret: MySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForHS256Algorithm

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: media-service-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
  topic:
    product-events: product-events

upload:
  directory: ./uploads/media
